Repository techequilla/community_app_boilerplate, pull requests merged in 2020-04, with the labels that each got.

#19 UI/UX for techequilla
  MockUp/logtechquilaa.pdf
Labels: rgsoc20, ui/ux

#20 Final design
  README.md
  mockup/mockups_new/Milestone.png
  mockup/mockups_new/Notification.png
  mockup/mockups_new/Post.png
  mockup/mockups_new/Profile.png
  mockup/mockups_new/Projects.png
  mockup/mockups_new/Sign In.png
  mockup/mockups_new/Sign Up.png
  mockup/mockups_new/TEAM.png
  mockup/mockups_new/project1.png
  mockup/mockups_new/project2.png
Labels: PR: unreviewed, rgsoc20, ui/ux

#23 added new app icon of techquilla logo
  community_app_boilerplate/.idea/.gitignore
  community_app_boilerplate/.idea/codeStyles/Project.xml
  community_app_boilerplate/.idea/community_app_boilerplate.iml
  community_app_boilerplate/.idea/libraries/Dart_Packages.xml
  community_app_boilerplate/.idea/libraries/Dart_SDK.xml
  community_app_boilerplate/.idea/libraries/Flutter_Plugins.xml
  community_app_boilerplate/.idea/misc.xml
  community_app_boilerplate/.idea/modules.xml
  community_app_boilerplate/.idea/vcs.xml
  community_app_boilerplate/android/app/src/main/AndroidManifest.xml
  community_app_boilerplate/android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  community_app_boilerplate/android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  community_app_boilerplate/android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  community_app_boilerplate/android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  community_app_boilerplate/android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  community_app_boilerplate/assets/icon/img.jpeg
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  community_app_boilerplate/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  community_app_boilerplate/pubspec.lock
  community_app_boilerplate/pubspec.yaml
Labels: PR: unreviewed, rgsoc20, ui/ux

#27 Teams updated, another version of logo added
  community_app_boilerplate/assets/icon/techequilla_app_icon_v2.png
  mockup/Team.png
Labels: PR: unreviewed, rgsoc20, ui/ux

#28 Removed path of deleted images(assets)
  community_app_boilerplate/pubspec.lock
  community_app_boilerplate/pubspec.yaml
Labels: PR: unreviewed, bug, rgsoc20

#33 Added font files according to UI
  community_app_boilerplate/assets/font/Averta_Bold.ttf
  community_app_boilerplate/assets/font/Averta_Regular.ttf
  community_app_boilerplate/assets/font/Averta_Semibold.ttf
  community_app_boilerplate/assets/font/Averta_Thin.ttf
  community_app_boilerplate/pubspec.lock
  community_app_boilerplate/pubspec.yaml
Labels: PR: unreviewed, ui/ux

#29 arranged all .gitignore files together in the master directory
  community_app_boilerplate/.gitignore
  community_app_boilerplate/.idea/.gitignore
  community_app_boilerplate/.idea/community_app_boilerplate.iml
  community_app_boilerplate/.idea/libraries/Dart_Packages.xml
  community_app_boilerplate/.idea/libraries/Flutter_Plugins.xml
  community_app_boilerplate/.idea/workspace.xml
  community_app_boilerplate/android/.gitignore
  community_app_boilerplate/ios/.gitignore
Labels: PR: unreviewed, bug, rgsoc20

#34 New Flutter Project
  community_app_boilerplate/lib/main.dart
  community_app_boilerplate/pubspec.lock
  community_app_boilerplate/pubspec.yaml
  community_app_boilerplate/test/widget_test.dart
Labels: PR: unreviewed
